global:
  scrape_interval: 15s  # Default scrape interval
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # This is Prometheus' own metrics endpoint

  - job_name: 'django'
    scrape_interval: 30s
    static_configs:
      - targets: ['127.0.0.1:8000']  # This should be the Django app's metrics endpoint

