# Generated by Django 5.1.1 on 2024-09-07 13:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "review_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rental_id", models.UUIDField(default=uuid.uuid4)),
                ("item_id", models.UUIDField(default=uuid.uuid4)),
                ("user_id", models.UUIDField(default=uuid.uuid4)),
                ("rating", models.IntegerField(default=5)),
                (
                    "comment",
                    models.TextField(default="Test comment. Happy sunday, funday"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
