# Generated by Django 5.1.1 on 2024-09-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='Test comment. Happy sunday, funday'),
        ),
    ]
