name: Code Coverage

# Trigger this workflow when a repository dispatch event occurs with event_type 'run-coverage'
on:
    repository_dispatch:
      types: [run-coverage]

jobs:
  code_coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Set up Python 3.12.6
      uses: actions/setup-python@v5  
      with:
        python-version: '3.12.6'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage  

    - name: Set up the database
      run: |
        python manage.py migrate

    - name: Run unit tests with coverage
      run: |
        coverage run --source='.' manage.py test reviews.tests.test_models reviews.tests.test_views --noinput
        coverage report 
        mkdir -p coverage_report
        coverage html -d coverage_report/  

    - name: Upload coverage report
      uses: actions/upload-artifact@v4  
      with:
        name: coverage-report
        path: coverage_report/
