name: Deploy Reviews Service to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.6' 

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to AWS EC2
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        RSYNC_RSH="ssh -o StrictHostKeyChecking=no" rsync -avz --progress --no-perms --no-owner --no-group --exclude={'db.sqlite3','media/','env/','tmp/','.git/','.github/'} . $USERNAME@$HOST:/home/ubuntu/irentstuff-reviews

        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << EOF
          cd /home/ubuntu/irentstuff-reviews
          source myenv/bin/activate
          pip install -r requirements.txt
          chmod +x manage.py
          python manage.py migrate
          # Restart the app using Supervisor
          sudo supervisorctl restart irentstuff_reviews
        EOF
