name: Lint with flake8 and black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.12.6
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.6'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=./env,./venv,./other_directories_to_exclude
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=./env,./venv,./other_directories_to_exclude

    - name: Format with black
      run: |
        black --check .
