name: Unit Tests

on: [push, pull_request]

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  

    - name: Set up Python 3.12.6
      uses: actions/setup-python@v5  
      with:
        python-version: '3.12.6' 

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up the database 
      run: |
        python manage.py migrate 

    - name: Run unit tests for models and views (using --noinput)
      run: |
        python manage.py test reviews.tests.test_models reviews.tests.test_views --noinput
    
    - name: Trigger Coverage Workflow
      if: success()  # Only trigger the next workflow if unit tests pass
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"run-coverage"}'